#!/usr/bin/env bash
# This script stops the 4-to_infinity_and_beyond process

# Find the PID of the 4-to_infinity_and_beyond process and kill it
pid=$(pgrep -f "4-to_infinity_and_beyond")
kill "$pid"
