#!/usr/bin/env bash
# Prints message 10 times, but adds different one at 9th time

count=1
while [ $count -le 10 ]
do
	echo "Best School"
	if [ $count -eq 9 ]; then
		echo "Hi"
	fi
	count=$((count + 1))
done
