#!/usr/bin/env bash
# This script displays all active IPv4 IPs on the machine.

# Use ifconfig to get IPv4 addresses, filter with grep, and refine output with cut
ifconfig | grep 'inet ' | awk '{print $2}'
