#!/usr/bin/env bash
# This script listens on port 98 on localhost and displays any received text.

# Listen on port 98 for incoming connections on localhost and output received messages.
nc -l 127.0.0.1 98
