#!/usr/bin/env bash
#Run Nginx as Nginx but better
sed -i "s/#user www-data/user nginx/" /etc/nginx/nginx.conf
sed -i -E "s/(listen.*)80 /\18080 /g" /etc/nginx/sites-available/default
chmod 644 /etc/nginx/nginx.conf
pkill apache2
sudo -u nginx service nginx restart
